v2.0.0 refactor
eastgenomics/eggd_tso500 pull request #10
Opened 2023-10-27 11:09 UTC by jethror1

## Summary

Refactor of original app to run TSO500 local app, this is now much faster (down from ~ 14 hours to 2 1/2 hours for a test run), and splits out the output files to distinct output fields for downstream automation.

![image](https://github.com/eastgenomics/eggd_tso500/assets/45037268/643fbc88-7fdd-4ece-99ad-8fecadf963fe)

## Changes
- switch running mode from sequential to scatter - gather (described on page 9 [here](https://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/trusight/trusight-oncology-500/trusight-oncology-500-local-app-v2.2-user-guide-1000000137777-01.pdf), using dx sub jobs to run the per sample analysis, and gathering outputs and doing final analysis in parent job
- create distinct output fields for bams, vcfs, combinedVariantOutput tsvs, TMB, MSI and metrics output files
- tarring of all intermediate log files and stdout/stderr to speed up upload / reduce total files output
- compressing of all intermediate genome VCFs which aren't routinely used (and should be compressed because its a VCF)
- additional options such as `-include_samples` and `-exclude_samples` to control running of the app

### TODO
- decide if final output directory structure is suitable
- decide if anymore output files need assigning to distinct output fields
- decide if any other inputs needed to modify behaviour

Example job: https://platform.dnanexus.com/projects/GZY91Qj4QJYbJ71xJv6KVyXP/monitor/job/GZxK9Qj4QJYVGB3bpG7qZqBY
Original 002 job for the above run: https://platform.dnanexus.com/projects/GZQQ9204bV2Xzq048x6fq28p/monitor/job/GZQQ92Q4bV2Xzq048x6fq28v

Fixes #4 #5 #7 #9

2023-10-27 16:42 UTC, corbin-chris requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: all files reviewed, 7 unresolved discussions (waiting on @Aisha-D, @Jay-Miles, @jethror1, and @mattgarner)

___
*[`dxapp.json` line 78 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhl-FQM1PlEapZ3udTq:-Nhl-FQM1PlEapZ3udTr:bfg052q) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/dxapp.json#L78)):*
> ```JSON
>       "name": "upload_demultiplex_output",
>       "label": "upload demultiplex output",
>       "help": "(Optional) control if to upload output from demultiplexing",
> ```

Phrasing a bit unclear to me - maybe something like '(Optional) controls whether demultiplexed files are retained (True) or discarded (False).'
___
*[`dxapp.json` line 110 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhl0Alu4NL0XwOSqucq:-Nhl0Alu4NL0XwOSqucr:b-dpmog) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/dxapp.json#L110)):*
> ```JSON
>       "name": "n_samples",
>       "label": "no. samples",
>       "help": "number of samples to limit running analysis for",
> ```

I find this help string a bit unclear and had to check the rest of the code to work it out, something like 'maximum number of SampleSheet samples to analyse' might be better
___
*[`README.md` line 15 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhl1Oen0kWYJVAAuGdw:-Nhl1Oen0kWYJVAAuGdx:b-90unkf) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/README.md#L15)):*
> ```Markdown
> - `samplesheet` (`file`) for the run if not present in the tarred inputs
> - `demultiplex_only` (`bool`) - flag to only demultiplex the runfolder
> - `upload_demultiplex_output` (`bool`; default: true): controls if to upload the demultiplexing output files
> ```

Same feedback as dxapp.json
___
*[`README.md` line 18 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhl1cj1-NYiPj1jpIpE:-Nhl1cj26z9OV9sd3JYm:bpra8r3) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/README.md#L18)):*
> ```Markdown
> - `analysis_options` (`str`) -  a string which can be passed to the ruo command line
> - `isNovaSeq` (`bool`; default: true) - passes the `-isNovaSeq` flag to the TSO500 local app for running on NovaSeq data
> - `scatter_instance` (`str`): DNAnexus instance type to use for the per sample analysis
> ```

Could you specify the default instance here, so people can tell whether they need to skip adding this option or not?
___
*[`README.md` line 31 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhl22t91qMLHYfV7fvo:-Nhl22t91qMLHYfV7fvp:b2s551x) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/README.md#L31)):*
> ```Markdown
> - hold parent job until all scatter jobs complete
> - gather up scatter job outputs and run final gather analysis step
> - upload all final output files and set app output spec 
> ```

There's a 'pre-demultiplexing' option (I think), could you outline very briefly what happens when that is used? Same for adding a small explainer to the 'What does this app output' section
___
*[`src/code.sh` line 160 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NhltKXj3sA6Ec59Mw3t:-NhltKXj3sA6Ec59Mw3u:b-hngjyi) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/src/code.sh#L160)):*
> ```Shell
>     if [[ "$n_samples" ]]; then
>         echo "Limiting analysis to ${n_samples} samples"
>         sample_rows=$(sed "2,${n_samples}p;d" <<< "${sample_rows}")
> ```

Is it meant to be 2, or 1 instead, after sed here? It's acting on sample_rows which already has the header row removed.
Will the sample_list echo'd below match with this new set of sample_rows? It doesn't look like sample_list gets trimmed down to only the n_samples amount.
___
*[`src/code.sh` line 287 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhlx4Mp26gN5lEf_ag3:-Nhlx4Mp26gN5lEf_ag4:b-6wrhpr) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/src/code.sh#L287)):*
> ```Shell
>         -name "*.out" -o \
>         -name "*.stderr" -o \
>         -name "*.stdout" -o\
> ```

Missing space after -o here


<!-- Sent from Reviewable.io -->

2023-10-29 10:28 UTC, mattgarner requested changes
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: all files reviewed, 18 unresolved discussions (waiting on @Aisha-D, @corbin-chris, @Jay-Miles, and @jethror1)

___
*[`dxapp.json` line 110 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhl0Alu4NL0XwOSqucq:-NhulYBh5fTmyzM1hXyS:b7is18k) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/dxapp.json#L110)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

I find this help string a bit unclear and had to check the rest of the code to work it out, something like 'maximum number of SampleSheet samples to analyse' might be better
</blockquote></details>

If we're updating this, perhaps also describe how the samples are selected (e.g. in samplesheet order? or however it works)
___
*[`dxapp.json` line 34 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NhuoiQXA9N2XyQ_Itxm:-NhuoiQY0UcCb63F8tao:b-l8u3i0) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/dxapp.json#L34)):*
> ```JSON
>     },
>     {
>       "name": "input_files",
> ```

Could this be more specific? There are other "input files", but those are not passed to this input



_Code quote:_
```JSON
input_files
```
___
*[`dxapp.json` line 45 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NhuijYX-pE0a_P4Jvrb:-NhuijYX-pE0a_P4Jvrc:besvwer) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/dxapp.json#L45)):*
> ```JSON
>       "name": "samplesheet",
>       "label": "samplesheet",
>       "help": "The SampleSheet used for demultiplexing",
> ```

1. Is this always the samplesheet used (given that samplesheet can be passed in multiple ways?
2. Should this test include a description of the hierarchy of samplesheet sources?

Edit re 1. This isn't really the samplesheet that was used, in that the samplesheet gets edited before use



_Code quote:_
```JSON
The SampleSheet used for demultiplexing
```
___
*[`dxapp.json` line 85 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhukev_AF4wn4LbfiPc:-Nhukev_AF4wn4LbfiPd:undefined) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/dxapp.json#L85)):*
> ```JSON
>     {
>       "name": "demultiplex_only",
>       "label": "demultiplex Only",
> ```





_Suggestion:_
```JSON
o

Sorry, it's annoying me :) 
```
___
*[`dxapp.json` line 178 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NhumKRu80E-rRVkkp84:-NhumKRu80E-rRVkkp85:b31ce4m) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/dxapp.json#L178)):*
> ```JSON
>     {
>       "name": "annotation",
>       "label": "annotation",
> ```

Could we elaborate?



_Suggestion:_
```JSON
annotation  
```
___
*[`src/code.sh` line 33 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NhurzOa4fVPWhWPHJxM:-NhurzOa4fVPWhWPHJxN:b7wha0q) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/src/code.sh#L33)):*
> ```Shell
> 
> 
> _get_input_files() {
> ```

Perhaps make the func name more specific (given that there are other input files which this doesn't get)



_Code quote:_
```Shell
_get_input_files
```
___
*[`src/code.sh` line 141 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhuuudz4Tyajk1Av2MR:-Nhuuudz4Tyajk1Av2MS:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/src/code.sh#L141)):*
> ```Shell
>         - filter samplesheet to specific samples (-iinclude_samples)
>         - limit samplesheet to first n samples (-in_samples)
>     
> ```

ws
___
*[`src/code.sh` line 166 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NhuvSj32RDFKknsUE60:-NhuvSj32RDFKknsUE61:undefined) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/src/code.sh#L166)):*
> ```Shell
>     if [[ "$include_samples" ]] || [[ "$exclude_samples" ]]; then
>         # first ensure any samples specified to include or exclude are
>         # a valid sample names from our samplesheet
> ```


___
*[`src/code.sh` line 192 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhuvf4x93z99r3eA577:-Nhuvf4x93z99r3eA578:b565as3) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/src/code.sh#L192)):*
> ```Shell
>         sample_rows=$(awk '!/'"$exclude"'/ {print $1}' <<< "$sample_rows")
>         sample_list=$(cut -d, -f1 <<< "$sample_rows")
>     fi
> ```

Perhaps note somewhere in the usage guidance that exclude takes priority over include



_Code quote:_
```Shell
    if [[ "$include_samples" ]]; then
        # retaining rows containing only those specified for given samples
        echo "-iinclude_samples specified: ${include_samples}"
        include=$(sed 's/,/|/g' <<< "$include_samples")
        sample_rows=$(awk '/'"$include"'/ {print $1}' <<< "$sample_rows")
        sample_list=$(cut -d, -f1 <<< "$sample_rows")
    fi

    if [[ "$exclude_samples" ]]; then
        # exclude rows containing only those specified for given samples
        echo -e "-iexclude_samples specified: ${exclude_samples}"
        exclude=$(sed 's/,/|/g' <<< "$exclude_samples")
        sample_rows=$(awk '!/'"$exclude"'/ {print $1}' <<< "$sample_rows")
        sample_list=$(cut -d, -f1 <<< "$sample_rows")
    fi
```
___
*[`src/code.sh` line 229 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NhuvxUw3Xwt2Z0QD9GG:-NhuvxUw3Xwt2Z0QD9GH:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/src/code.sh#L229)):*
> ```Shell
>         | sort -k2 -n)
>     set -x
>     
> ```

ws



_Code quote:_
```Shell
···
```
___
*[`src/code.sh` line 241 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhuw3-UE660IfkF1xV9:-Nhuw3-UE660IfkF1xVA:b32x0h) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/src/code.sh#L241)):*
> ```Shell
> 
>     Default directory structure downloaded from all scatter jobs:
>     
> ```

ws



_Code quote:_
```Shell
···
```
___
*[`src/code.sh` line 377 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhuwpqb3BQTVDoudI-e:-Nhuwpqb3BQTVDoudI-f:b-wx5o90) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/src/code.sh#L377)):*
> ```Shell
>     find /home/dnanexus/out/ -type f | xargs -P ${UPLOAD_THREADS} -n1 -I{} bash -c \
>         "_upload_single_file {} analysis_folder false"
>     
> ```

ws

I'm going to skip flagging the rest of these.


<!-- Sent from Reviewable.io -->

2023-10-30 09:55 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: 2 of 5 files reviewed, 18 unresolved discussions (waiting on @Aisha-D, @corbin-chris, @Jay-Miles, and @mattgarner)

___
*[`dxapp.json` line 78 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhl-FQM1PlEapZ3udTq:-NhztVXi-bDkVh75rP7k:b4m3l2x) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/dxapp.json#L78)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Phrasing a bit unclear to me - maybe something like '(Optional) controls whether demultiplexed files are retained (True) or discarded (False).'
</blockquote></details>

makes sense, changed it
___
*[`dxapp.json` line 110 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhl0Alu4NL0XwOSqucq:-NhzuDaT2hfmpjIB5nSq:bb7f2mf) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/dxapp.json#L110)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

If we're updating this, perhaps also describe how the samples are selected (e.g. in samplesheet order? or however it works)
</blockquote></details>

done
___
*[`dxapp.json` line 34 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NhuoiQXA9N2XyQ_Itxm:-NhzspVK4ysOt-tMJZ7z:b-po5wpu) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/dxapp.json#L34)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could this be more specific? There are other "input files", but those are not passed to this input
</blockquote></details>

yeah this used to be tars or fastqs and is just tars now, have changed to `run_tar_data`
___
*[`dxapp.json` line 45 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NhuijYX-pE0a_P4Jvrb:-NhzszF49RQitISZBU0v:b92rw8o) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/dxapp.json#L45)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

1. Is this always the samplesheet used (given that samplesheet can be passed in multiple ways?
2. Should this test include a description of the hierarchy of samplesheet sources?

Edit re 1. This isn't really the samplesheet that was used, in that the samplesheet gets edited before use
</blockquote></details>

yeah this is left over from before, have now updated it
___
*[`dxapp.json` line 85 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhukev_AF4wn4LbfiPc:-NhztZpw4uUFnn0MNYHB:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/dxapp.json#L85)):*
> ```JSON
>     {
>       "name": "demultiplex_only",
>       "label": "demultiplex Only",
> ```

Done.
___
*[`dxapp.json` line 178 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NhumKRu80E-rRVkkp84:-NhzuYT88T_Coms28qk7:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/dxapp.json#L178)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Could we elaborate?
</blockquote></details>

Done.
___
*[`README.md` line 15 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhl1Oen0kWYJVAAuGdw:-NhzvAyuBE3AVRVa6Q6A:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/README.md#L15)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Same feedback as dxapp.json
</blockquote></details>

Done.
___
*[`README.md` line 18 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhl1cj1-NYiPj1jpIpE:-NhzwMni-HpivFg478CW:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/README.md#L18)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Could you specify the default instance here, so people can tell whether they need to skip adding this option or not?
</blockquote></details>

Done.
___
*[`README.md` line 31 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhl22t91qMLHYfV7fvo:-NhzwWMlBvXKlULL88Dl:b-x7ap86) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/README.md#L31)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

There's a 'pre-demultiplexing' option (I think), could you outline very briefly what happens when that is used? Same for adding a small explainer to the 'What does this app output' section
</blockquote></details>

is this relating to parsing and bodging the samplesheet? if so I have added this
___
*[`src/code.sh` line 160 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NhltKXj3sA6Ec59Mw3t:-NhzzP1sAVWVmYYs3aul:bs0l3g2) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/src/code.sh#L160)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Is it meant to be 2, or 1 instead, after sed here? It's acting on sample_rows which already has the header row removed.
Will the sample_list echo'd below match with this new set of sample_rows? It doesn't look like sample_list gets trimmed down to only the n_samples amount.
</blockquote></details>

good catch yeah, I had this before include the header line but switched it when I added include/exclude
___
*[`src/code.sh` line 287 at r1](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhlx4Mp26gN5lEf_ag3:-Ni--VVq26cESDaYqRzi:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/7d305b5a1d5da9f9e2facfc68a2ca5d179ba964c/src/code.sh#L287)):*
<details><summary><i>Previously, corbin-chris (Chris Corbin) wrote…</i></summary><blockquote>

Missing space after -o here
</blockquote></details>

Done.
___
*[`src/code.sh` line 33 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NhurzOa4fVPWhWPHJxM:-Nhzx1SL6f0MjJZWBZux:bq6q0md) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/src/code.sh#L33)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Perhaps make the func name more specific (given that there are other input files which this doesn't get)
</blockquote></details>

changed this to `_get_run_data()`
___
*[`src/code.sh` line 141 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhuuudz4Tyajk1Av2MR:-NhzyZR33L-Rxd4IVy9l:bfy74qw) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/src/code.sh#L141)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

ws
</blockquote></details>

boo I had the extension disabled, have fixed them all now
___
*[`src/code.sh` line 166 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NhuvSj32RDFKknsUE60:-NhzzVgb7r20-prK5rPS:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/src/code.sh#L166)):*
> ```Shell
>     if [[ "$include_samples" ]] || [[ "$exclude_samples" ]]; then
>         # first ensure any samples specified to include or exclude are
>         # a valid sample names from our samplesheet
> ```

Done.
___
*[`src/code.sh` line 192 at r2](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Nhuvf4x93z99r3eA577:-Ni--68t27kGUXI91W7c:b-d16iod) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/554582f58f86e7bf2cfd359cd9b2648d45ab87fb/src/code.sh#L192)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Perhaps note somewhere in the usage guidance that exclude takes priority over include
</blockquote></details>

they should be mutually exclusive, have added a check and exit for t [...]

2023-10-30 12:02 UTC, Aisha-D requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: 2 of 5 files reviewed, 20 unresolved discussions (waiting on @corbin-chris, @Jay-Miles, @jethror1, and @mattgarner)

___
*[`src/code.sh` line 129 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Ni-QFgB7ifHGcGkPuTa:-Ni-QFgC2E1IpWBslhUh:bcudy01) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/463ba9aae0dedec7734fa44e73f73aea2f72b71d/src/code.sh#L129)):*
> ```Shell
>     Parse the sample names from the samplesheet into variable "sample_list"
> 
>     If specified, can also optionally:
> ```

these parameters not used in this function
___
*[`src/code.sh` line 136 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Ni-PrCgEg8oCpsfKnGP:-Ni-PrCgEg8oCpsfKnGQ:b9wa1ag) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/463ba9aae0dedec7734fa44e73f73aea2f72b71d/src/code.sh#L136)):*
> ```Shell
>     # parse list of sample names from samplesheet
>     sample_rows=$(sed -e '1,/Sample_ID/ d' runfolder/SampleSheet.csv)
>     sample_list=$(cut -d, -f1 <<< "$sample_rows")
> ```

Why the first column? No effect in current method but the old sample name convention  used to name output folder on the Pair_ID which is 9th column, assuming that is what the sample_list will be used for


<!-- Sent from Reviewable.io -->

2023-10-30 14:39 UTC, corbin-chris approved these changes
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: all files reviewed, 13 unresolved discussions (waiting on @Jay-Miles, @jethror1, and @mattgarner)



<!-- Sent from Reviewable.io -->

2023-10-30 14:39 UTC, corbin-chris approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: all files reviewed, 13 unresolved discussions (waiting on @Jay-Miles, @jethror1, and @mattgarner)



<!-- Sent from Reviewable.io -->

2023-10-30 21:38 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: 3 of 5 files reviewed, 13 unresolved discussions (waiting on @Aisha-D, @corbin-chris, @Jay-Miles, and @mattgarner)

___
*[`src/code.sh` line 129 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Ni-QFgB7ifHGcGkPuTa:-Ni-jIPk4ikktcc720Dk:b-8d4tc6) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/463ba9aae0dedec7734fa44e73f73aea2f72b71d/src/code.sh#L129)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

these parameters not used in this function
</blockquote></details>

good point, removed
___
*[`src/code.sh` line 136 at r3](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-Ni-PrCgEg8oCpsfKnGP:-Ni-jOOL5mdlExffyQeY:b-811jmy) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/463ba9aae0dedec7734fa44e73f73aea2f72b71d/src/code.sh#L136)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

Why the first column? No effect in current method but the old sample name convention  used to name output folder on the Pair_ID which is 9th column, assuming that is what the sample_list will be used for
</blockquote></details>

switched this to parse IDs to use for launching jobs from Pair_ID column, mostly in these 2 commits:
- https://github.com/eastgenomics/eggd_tso500/commit/79ab3eb8e2b2465e4a151c656771cb055b7de8c7
- https://github.com/eastgenomics/eggd_tso500/commit/7288198214416949ff2f4bd31dae28a3e723a07f

Example job of all unique pair IDs: https://platform.dnanexus.com/projects/GZY91Qj4QJYbJ71xJv6KVyXP/monitor/job/GZzxyF84QJYXF4BJ9ZBqX650

Example job of 2 samples with shared Pair_ID: https://platform.dnanexus.com/projects/GZY91Qj4QJYbJ71xJv6KVyXP/monitor/job/Gb023384QJYgJk5Ygg7zpV5f


<!-- Sent from Reviewable.io -->

2023-11-02 10:14 UTC, Aisha-D requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: 2 of 5 files reviewed, 13 unresolved discussions (waiting on @corbin-chris, @Jay-Miles, @jethror1, and @mattgarner)

___
*[`src/code.sh` line 514 at r7](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NiEW-2DDIOUA8Af59fe:-NiEW-2DDIOUA8Af59ff:b4fyh1p) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/6d17abc6273f5ba8a543ba6c393cce0b76db421b/src/code.sh#L514)):*
> ```Shell
> _upload_demultiplex_output() {
>     : '''
>     Upload output of demultiplexing into project, this will be called
> ```

container :) 
___
*[`src/code.sh` line 520 at r7](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NiEWFIh1WWMYQjt-zWJ:-NiEWFIh1WWMYQjt-zWK:bfqfto) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/6d17abc6273f5ba8a543ba6c393cce0b76db421b/src/code.sh#L520)):*
> ```Shell
>     echo "Uploading demultiplexing output"
>     SECONDS=0
>     export -f _upload_single_file
> ```

so this function will be exported to the child job or container? maybe some comments pleaseeee


<!-- Sent from Reviewable.io -->

2023-11-02 10:24 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: 2 of 5 files reviewed, 13 unresolved discussions (waiting on @Aisha-D, @corbin-chris, @Jay-Miles, and @mattgarner)

___
*[`src/code.sh` line 514 at r7](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NiEW-2DDIOUA8Af59fe:-NiEYzqRDurMxcuNExOl:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/6d17abc6273f5ba8a543ba6c393cce0b76db421b/src/code.sh#L514)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

container :)
</blockquote></details>

Done.
___
*[`src/code.sh` line 520 at r7](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NiEWFIh1WWMYQjt-zWJ:-NiEYccw7TELPJktVqc5:b81b2x5) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/6d17abc6273f5ba8a543ba6c393cce0b76db421b/src/code.sh#L520)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

so this function will be exported to the child job or container? maybe some comments pleaseeee
</blockquote></details>

export is required for being able to access a local function in xargs, all functions are available to the sub job, added a comment to each instance of this


<!-- Sent from Reviewable.io -->

2023-11-02 10:41 UTC, Aisha-D requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: 2 of 5 files reviewed, 15 unresolved discussions (waiting on @corbin-chris, @Jay-Miles, @jethror1, and @mattgarner)

___
*[`src/code.sh` line 72 at r7](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NiEb46m-_tnMWWbkDkj:-NiEb46m-_tnMWWbkDkk:b4vy72m) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/6d17abc6273f5ba8a543ba6c393cce0b76db421b/src/code.sh#L72)):*
> ```Shell
>     # only take a few seconds for this to happen until dxpy is updated to
>     # actually do proper retries like sane people
>     echo "Waiting 60 seconds to ensure all files are hopefully in a closed state..."
> ```

i cant see a command that downloads the files... maybe i'm being slow....
Also can't  a check be done to ensure all files are in a closed state before commencing? 
___
*[`src/code.sh` line 588 at r7](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NiEYSceBJwgRwW0eQsZ:-NiEYSceBJwgRwW0eQs_:bchtiqx) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/6d17abc6273f5ba8a543ba6c393cce0b76db421b/src/code.sh#L588)):*
> ```Shell
>     This function will be launched as a sub job within the scope of
>     the main TSO500 job, it sets up the job environment, runs the
>     local app and uploads output to the project to then continue
> ```

upload to project or container?


<!-- Sent from Reviewable.io -->

2023-11-02 11:01 UTC, Aisha-D requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: 2 of 5 files reviewed, 14 unresolved discussions (waiting on @corbin-chris, @Jay-Miles, @jethror1, and @mattgarner)

___
*[`src/code.sh` line 418 at r8](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NiEfKKa2CQZIfWc6fdI:-NiEfKKbDmIGewIGQWeG:bm6cilw) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/d67846f0040900ea5319df91fc5ce36ffd690b26/src/code.sh#L418)):*
> ```Shell
> 
>     The rest of the per sample analysis and gather step files are then uploaded
>     in parallel to the "analysis_folder" output field.
> ```

does this reflect the current changes done to the directory structure ie does the analysis folder exist?


<!-- Sent from Reviewable.io -->

2023-11-02 11:09 UTC, Aisha-D requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: 2 of 5 files reviewed, 15 unresolved discussions (waiting on @corbin-chris, @Jay-Miles, @jethror1, and @mattgarner)

___
*[`dxapp.json` line 5 at r8](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NiEi5ZDAIhuoC9Oqr7l:-NiEi5ZDAIhuoC9Oqr7m:b-b5ojdn) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/d67846f0040900ea5319df91fc5ce36ffd690b26/dxapp.json#L5)):*
> ```JSON
>   "title": "eggd_tso500",
>   "summary": "Somatic variant calling for DNA & RNA samples using TSO500 local app",
>   "dxapi": "1.0.0",
> ```

is this needed - it hasnt been bumped up?


<!-- Sent from Reviewable.io -->

2023-11-02 11:28 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: 2 of 5 files reviewed, 15 unresolved discussions (waiting on @Aisha-D, @corbin-chris, @Jay-Miles, and @mattgarner)

___
*[`dxapp.json` line 5 at r8](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NiEi5ZDAIhuoC9Oqr7l:-NiEkPOI40UorRfFucJE:b-epbzxl) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/d67846f0040900ea5319df91fc5ce36ffd690b26/dxapp.json#L5)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

is this needed - it hasnt been bumped up?
</blockquote></details>

as in the dxapi field? I think so? its the same in our other apps, the app version has gone from v1.2.0->v2.0.0
___
*[`src/code.sh` line 72 at r7](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NiEb46m-_tnMWWbkDkj:-NiEkjzr2UDck-NI4f4e:bdrbwzz) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/6d17abc6273f5ba8a543ba6c393cce0b76db421b/src/code.sh#L72)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

i cant see a command that downloads the files... maybe i'm being slow....
Also can't  a check be done to ensure all files are in a closed state before commencing?
</blockquote></details>

downloading is done here: https://github.com/eastgenomics/eggd_tso500/blob/d67846f0040900ea5319df91fc5ce36ffd690b26/src/code.sh#L89

re the file state - I want to push back on DNAnexus with this and I think that dx download should try and wait and not just skip, have a ticket open with support about this.

I added this as I had a job that failed as a file hadn't closed from the last scatter job, it should be pretty quick to close so just going to wait for it to happen
___
*[`src/code.sh` line 588 at r7](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NiEYSceBJwgRwW0eQsZ:-NiEmkM1513A3kBn3qmL:bj8nt0g) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/6d17abc6273f5ba8a543ba6c393cce0b76db421b/src/code.sh#L588)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

upload to project or container?
</blockquote></details>

yep - changed
___
*[`src/code.sh` line 418 at r8](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NiEfKKa2CQZIfWc6fdI:-NiElPdoEIUm0LGFnYc4:b-pjojvk) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/d67846f0040900ea5319df91fc5ce36ffd690b26/src/code.sh#L418)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

does this reflect the current changes done to the directory structure ie does the analysis folder exist?
</blockquote></details>

yep, analysis_folder is the output field of 'all other output files'


<!-- Sent from Reviewable.io -->

2023-11-02 15:32 UTC, mattgarner requested changes
> Reviewed 1 of 3 files at r7, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: all files reviewed, 2 unresolved discussions (waiting on @Aisha-D, @Jay-Miles, and @jethror1)

___
*[`README.md` line 10 at r10](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NiFdXEJDwHMBn2inufn:-NiFdXEJDwHMBn2inufo:undefined) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/0283dc7cab82c8dc0cbb6dbeefdbf38d35c486bb/README.md#L10)):*
> ```Markdown
> ### Required
> - `TSO500_ruo` (`file`) - a zip file (originally provided by Illumina) containing the TSO500 local analysis app.
> - `input_files` (`array:files`) - raw sequencing data in tar files
> ```





_Suggestion:_
```Markdown
run_tar_data
```


<!-- Sent from Reviewable.io -->

2023-11-02 16:41 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @Aisha-D, @Jay-Miles, and @mattgarner)

___
*[`README.md` line 10 at r10](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-NiFdXEJDwHMBn2inufn:-NiFuBx01qpvlxQByScS:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_tso500/blob/0283dc7cab82c8dc0cbb6dbeefdbf38d35c486bb/README.md#L10)):*
> ```Markdown
> ### Required
> - `TSO500_ruo` (`file`) - a zip file (originally provided by Illumina) containing the TSO500 local analysis app.
> - `input_files` (`array:files`) - raw sequencing data in tar files
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-11-02 16:58 UTC, mattgarner approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: all files reviewed, 1 unresolved discussion (waiting on @Aisha-D and @Jay-Miles)



<!-- Sent from Reviewable.io -->

2023-11-02 16:59 UTC, mattgarner approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10)* status: all files reviewed, 1 unresolved discussion (waiting on @Aisha-D and @Jay-Miles)



<!-- Sent from Reviewable.io -->

2023-11-02 17:38 UTC, Aisha-D approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_tso500/10#-:-NiG6LjRB13H_rP7Y1Yr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Jay-Miles)



<!-- Sent from Reviewable.io -->

2023-11-02 17:44 UTC, merged